-- Baseline schema: users, videos (incl. processing-pipeline columns), video_tags

CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE videos (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(255) NOT NULL,
    filename           VARCHAR(255) NOT NULL,
    content_type       VARCHAR(255) NOT NULL,
    size               BIGINT,
    upload_date        TIMESTAMP(6) NOT NULL,
    duration_seconds   DOUBLE PRECISION,
    width              INTEGER,
    height             INTEGER,
    description        TEXT,
    status             VARCHAR(255) NOT NULL,
    thumbnail_filename VARCHAR(255),
    user_id            BIGINT NOT NULL REFERENCES users (id)
);

CREATE TABLE video_tags (
    video_id BIGINT NOT NULL REFERENCES videos (id),
    tag      VARCHAR(255)
);

CREATE INDEX idx_videos_user_id ON videos (user_id);
